//♭♯
export const Chord = [
  { name: 'C', notes: '1 3 5', type: 'major', origin: 'C' },
  { name: 'Cm', notes: '1 ♭3 5', type: 'minor', origin: 'C' },
  { name: 'Caug', notes: '1 3 ♯5', type: 'aug', origin: 'C' },
  { name: 'Cdim', notes: '1 ♭3 ♭5', type: 'dim', origin: 'C' },
  { name: 'D', notes: '2 ♯4 6', type: 'major', origin: 'D' },
  { name: 'Dm', notes: '2 4 6', type: 'minor', origin: 'D' },
  { name: 'Daug', notes: '2 ♯4 ♯6', type: 'aug', origin: 'D' },
  { name: 'Ddim', notes: '2 4 ♭6', type: 'dim', origin: 'D' },
  { name: 'E', notes: '3 ♯5 7', type: 'major', origin: 'E' },
  { name: 'Em', notes: '3 5 7', type: 'minor', origin: 'E' },
  { name: 'Eaug', notes: '3 ♯5 ♯7', type: 'aug', origin: 'E' },
  { name: 'Edim', notes: '3 5 ♭7', type: 'dim', origin: 'E' },
  { name: 'F', notes: '4 6 1', type: 'major', origin: 'F' },
  { name: 'Fm', notes: '4 ♭6 1', type: 'minor', origin: 'F' },
  { name: 'Faug', notes: '4 6 ♯1', type: 'aug', origin: 'F' },
  { name: 'Fdim', notes: '4 ♭6 ♭1', type: 'dim', origin: 'F' },
  { name: 'G', notes: '5 7 2', type: 'major', origin: 'G' },
  { name: 'Gm', notes: '5 ♭7 2', type: 'minor', origin: 'G' },
  { name: 'Gaug', notes: '5 7 ♯2', type: 'aug', origin: 'G' },
  { name: 'Gdim', notes: '5 ♭7 ♭2', type: 'dim', origin: 'G' },
  { name: 'A', notes: '6 ♯1 3', type: 'major', origin: 'A' },
  { name: 'Am', notes: '6 1 3', type: 'minor', origin: 'A' },
  { name: 'Aaug', notes: '6 ♯1 ♯3', type: 'aug', origin: 'A' },
  { name: 'Adim', notes: '6 1 ♭3', type: 'dim', origin: 'A' },
  { name: 'B', notes: '7 ♯2 ♯4', type: 'major', origin: 'B' },
  { name: 'Bm', notes: '7 2 ♯4', type: 'minor', origin: 'B' },
  { name: 'Baug', notes: '7 ♯2 x4 (重升4)', type: 'aug', origin: 'B' },
  { name: 'Bdim', notes: '7 2 4', type: 'dim', origin: 'B' },
]